---
services: docker

env:
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: debian9
  - distro: debian8

script:
  # Configure test script so we can run extra tests after playbook is run
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/chriswayg/7cf5afda283252219c37c447ccf3ad88/raw/199f22ced6dd31c948ab2fb6e647a8cd612d337e/ansible-role-test.sh
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
