---
- name: Check if gitignore exists.
  stat:
    path: "/etc/.gitignore"
  register: p

- name: Create gitignore, if it does not exist.
  file:
    path: /etc/.gitignore
    state: touch
  when: not p.stat.exists

- name: Add entries to .gitignore (slow)
  lineinfile:
    dest: '/etc/.gitignore'
    line: "{{ item }}"
    state: present
  with_items: "{{ etckeeper_gitignore }}"
  when: etckeeper_vcs == 'git'
  register: gitignore_status

- name: Install etckeeper.
  apt:
    name: etckeeper
    state: present
    install_recommends: no
    update_cache: yes
  notify: Record changes in etckeeper

- name: Configure etckeeper disable bzr.
  lineinfile:
    dest: /etc/etckeeper/etckeeper.conf
    regexp: '^.*(VCS="bzr")'
    line: '#\1'
    backrefs: yes
  register: bzr_config_status

- name: Configure etckeeper enable VCS.
  lineinfile:
    dest: /etc/etckeeper/etckeeper.conf
    regexp: '^.*(VCS="{{ etckeeper_vcs }}")'
    line: '\1'
    backrefs: yes
  register: vcs_config_status

- name: Initialize etckeeper repository.
  command: etckeeper init
  when: bzr_config_status is changed or vcs_config_status is changed

## Should check first, if theses items actually exist, and only remove these.
- name: Remove new .gitignore items from tracking.
  shell: cd /etc/ && git reset "{{ item }}"
  with_items: "{{ etckeeper_gitignore }}"
  when: etckeeper_vcs == 'git' and gitignore_status is changed

- name: Install tig (git ncurses interface).
  apt:
    name: tig
    state: present
  when:
    - etckeeper_vcs == 'git'
    - etckeeper_install_tig

- name: Git user configuration (run only once).
  # Fixes: when trying to reset author: fatal: You have nothing to amend.
  #shell: cd /etc/ && git config --global user.name "{{ etckeeper_git_user_name }}"
  #       && git config --global user.email "{{ etckeeper_git_user_email }}"
  #       && git commit --amend --reset-author -m "configure author"
  #       && touch /etc/.etckeeper.initialized
  shell: >
    cd /etc/ && git config --global user.name "{{ etckeeper_git_user_name }}"
    && git config --global user.email "{{ etckeeper_git_user_email }}"
    && touch /etc/.etckeeper.initialized

  args:
    creates: /etc/.etckeeper.initialized
  when: etckeeper_vcs == 'git'
