---
- name: Check if gitignore exists.
  stat:
    path: "/etc/.gitignore"
  register: p

- name: Create gitignore, if it does not exist.
  file:
    path: /etc/.gitignore
    state: touch
  when: not p.stat.exists

- name: Add entries to .gitignore
  blockinfile:
    path: '/etc/.gitignore'
    block: |
      {{ etckeeper_gitignore }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  register: gitignore_status

- name: Install etckeeper.
  apt:
    name: etckeeper
    state: present
    install_recommends: no
    update_cache: yes

# By default, etckeeper uses git. Debian and Ubuntu use git by default.
# thus this should not be needed
# - name: Configure etckeeper disable bzr.
#   lineinfile:
#     dest: /etc/etckeeper/etckeeper.conf
#     regexp: '^.*(VCS="bzr")'
#     line: '#\1'
#     backrefs: yes
#
# - name: Configure etckeeper enable VCS.
#   lineinfile:
#     dest: /etc/etckeeper/etckeeper.conf
#     regexp: '^.*(VCS="{{ etckeeper_vcs }}")'
#     line: '\1'
#     backrefs: yes

# `etckeeper init` is normally automatically performed during package installation.
- name:  Initialize etckeeper repository.
  shell: etckeeper init
  args:
    chdir: /etc/
    creates: /etc/.etckeeper

# sometimes git complains, when this is not configured
- name:  Git user configuration (runs only once).
  shell: |
    etckeeper init
    git config --global user.name "{{ etckeeper_git_user_name }}"
    git config --global user.email "{{ etckeeper_git_user_email }}"
    touch /etc/.ansible-etckeeper.configured
  args:
    chdir: /etc/
    creates: /etc/.ansible-etckeeper.configured

# 'Ignore files that have already been committed to a Git repository' (stackoverflow)
# TODO fix: The commit gives an error when there is nothing to commit, which can be ignored.
- name: Remove new gitignore items from tracking
  shell: |
    git rm -r --quiet --cached .
    git add .
    git commit -m "Cleanup git-ignore files" || true
  args:
    chdir: /etc/
  when: gitignore_status.changed|bool

- name: Install tig (git ncurses interface).
  apt:
    name: tig
    state: present
  when: etckeeper_install_tig|bool
