---
# tasks file for etckeeper

- name: Install and configure etckeeper
  include_tasks: install.yml
  when: install|bool

- name: Record changes in etckeeper
  shell: "if etckeeper unclean; then etckeeper commit '{{ etckeeper_message }}'; fi"
  register: etckeeper_result
  changed_when: etckeeper_result.stdout.find('changed') != -1
  when: commit|bool

- name: Debug etckeeper_message
  debug:
    var: etckeeper_message
  when: commit|bool

- name: Debug etckeeper_result
  debug:
    var: etckeeper_result
  when: commit|bool
