---
# handlers file for etckeeper

- name: Record changes in etckeeper
  shell: "if etckeeper unclean; then etckeeper commit '{{ etckeeper_message }}'; fi"
  register: etckeeper_result
  changed_when: etckeeper_result.stdout.find('changed') != -1
